/******  Db Version 3  ******/
UPDATE DB_Version SET [DB_Version] = 3
GO

ALTER VIEW [dbo].[Location]
AS
SELECT     LOC_NUM AS LocationId, LOC_NAME AS Name, LOC_NAME_SHORT AS NameShort, LOC_ADDR_STREET AS Street, LOC_ADDR_CITY AS City, 
                      LOC_ADDR_ZIP_CODE AS ZipCode, REPLACE(LOC_PHONE_NUM_OFFICE, ')', ') ') AS PhoneNumOffice, ISNULL(LOC_REGN_CODE, 0) AS RegionId
FROM         dbo.V_LOCATION
GO

ALTER VIEW [dbo].[V_LOCATION]
AS
SELECT     LOC_NUM, LOC_NAME, LOC_NAME_SHORT, LOC_ADDR_STREET, LOC_ADDR_CITY, LOC_ADDR_ZIP_CODE, LOC_PHONE_NUM_OFFICE, LOC_REGN_CODE
FROM         DW_Locations.dbo.LOCATION
WHERE     (LOC_REGN_CODE BETWEEN '0' AND '6') OR
                      (LOC_NUM = '9029')
GO

ALTER VIEW [dbo].[Region]
AS
SELECT     CAST(REGN_CODE AS INT) AS RegionId, RTRIM(REGN_NAME) AS Name
FROM         dbo.V_REGION AS Region_1
GO

ALTER VIEW [dbo].[V_REGION]
AS
SELECT     REGN_CODE, REGN_NAME
FROM         DW_Locations.dbo.REGION
WHERE     (REGN_CODE BETWEEN '1' AND '6')
UNION
SELECT     0 AS REGN_CODE, 'REGION' AS REGN_NAME
GO