/******  Db Version 7  ******/
UPDATE DB_Version SET [DB_Version] = 7
GO

ALTER PROCEDURE [dbo].[GetCoverage]
	@userId int
AS
BEGIN
	SET NOCOUNT ON;

	SELECT DISTINCT [Level], Subject, V_CERTIFICATE.Subject_of_coverage_description as 'SubjectName', V_CERTIFICATE_LEVEL.CERTIFICATE_LEVEL_DESC as 'LevelName', CASE WHEN V_EMPLOYEE_CERTIFICATE.CERTIF_EXPIRE_YEAR_1 > 0 THEN V_EMPLOYEE_CERTIFICATE.CERTIF_EXPIRE_YEAR_1 ELSE V_EMPLOYEE_CERTIFICATE.DIST_CERTIF_EXPIRE_YEAR_1 END as 'ExpireYear'
	FROM Coverage
	LEFT JOIN V_CERTIFICATE ON V_CERTIFICATE.Subject_of_coverage = Coverage.Subject
	LEFT JOIN V_CERTIFICATE_LEVEL ON V_CERTIFICATE_LEVEL.CERTIFICATE_LEVEL_CODE = Coverage.[Level]
	LEFT JOIN V_EMPLOYEE_CERTIFICATE ON V_EMPLOYEE_CERTIFICATE.EMPLOYEE_NUMBER = Coverage.EMPLOYEE_NUMBER
	WHERE Coverage.EMPLOYEE_NUMBER = @userId AND Subject <> '000'
END
GO
