
// Generated by MyGeneration Version # (1.1.5.1)

using System;

namespace Miami.Substitute.Dal
{
    public class Grade : Miami.Substitute.Dal.Generated.Grade
    {
        public Grade() 
        {
            this.ConnectionString = ConnectionStringProvider.ConnectionString;
        }

        // Place your custom code here.
    }
}
