
// Generated by MyGeneration Version # (1.1.5.1)

using System;

namespace Miami.Substitute.Dal
{
    public class Teacher : Miami.Substitute.Dal.Generated.Teacher
    {
        public Teacher()
        {
            this.ConnectionString = ConnectionStringProvider.ConnectionString;
        }

        // Place your custom code here.
    }
}
