
// Generated by MyGeneration Version # (1.1.5.1)

using System;

namespace Miami.Substitute.Dal
{
    public class UserProfile : Miami.Substitute.Dal.Generated.UserProfile
	{		
		public UserProfile() 
        {
            this.ConnectionString = ConnectionStringProvider.ConnectionString;
        }
		// Place your custom code here.
	}
}
