/*
'===============================================================================
'  Generated From - CSharp_EasyObject_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL      = SQL_DAAB_StoredProcs.vbgen
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easily done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.1.5.1)

using System;
using System.Data;
using System.Data.Common;
using System.Configuration;
using System.Collections;
using System.Collections.Specialized;
using System.Xml;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Data;
using NCI.EasyObjects;

namespace Miami.Substitute.Dal.Generated
{

    #region Schema

    public class GradeSchema : NCI.EasyObjects.Schema
    {
        private static ArrayList _entries;
        public static SchemaItem GradeId = new SchemaItem("GradeId", DbType.Int32, false, false, false, true, true, false);
        public static SchemaItem Name = new SchemaItem("Name", DbType.String, SchemaItemJustify.None, 255, true, false, false, false);

        public override ArrayList SchemaEntries
        {
            get
            {
                if (_entries == null)
                {
                    _entries = new ArrayList();
                    _entries.Add(GradeSchema.GradeId);
                    _entries.Add(GradeSchema.Name);
                }
                return _entries;
            }
        }
    }
    #endregion

    public abstract class Grade : EasyObject
    {

        public Grade()
        {
            GradeSchema _schema = new GradeSchema();
            this.SchemaEntries = _schema.SchemaEntries;
            this.SchemaGlobal = "dbo";
        }

        public override void FlushData()
        {
            this._whereClause = null;
            this._aggregateClause = null;
            base.FlushData();
        }

        /// <summary>
        /// Loads the business object with info from the database, based on the requested primary key.
        /// </summary>
        /// <param name="GradeId"></param>
        /// <returns>A Boolean indicating success or failure of the query</returns>
        public bool LoadByPrimaryKey(int GradeId)
        {
            switch (this.DefaultCommandType)
            {
                case CommandType.StoredProcedure:
                    ListDictionary parameters = new ListDictionary();

                    // Add in parameters
                    parameters.Add(GradeSchema.GradeId.FieldName, GradeId);

                    return base.LoadFromSql(this.SchemaStoredProcedureWithSeparator + "daab_GetGrade", parameters, CommandType.StoredProcedure);

                case CommandType.Text:
                    this.Query.ClearAll();
                    this.Where.WhereClauseReset();
                    this.Where.GradeId.Value = GradeId;
                    return this.Query.Load();

                default:
                    throw new ArgumentException("Invalid CommandType", "commandType");
            }
        }

        /// <summary>
        /// Loads all records from the table.
        /// </summary>
        /// <returns>A Boolean indicating success or failure of the query</returns>
        public bool LoadAll()
        {
            switch (this.DefaultCommandType)
            {
                case CommandType.StoredProcedure:
                    return base.LoadFromSql(this.SchemaStoredProcedureWithSeparator + "daab_GetAllGrade", null, CommandType.StoredProcedure);

                case CommandType.Text:
                    this.Query.ClearAll();
                    this.Where.WhereClauseReset();
                    return this.Query.Load();

                default:
                    throw new ArgumentException("Invalid CommandType", "commandType");
            }
        }

        /// <summary>
        /// Adds a new record to the internal table.
        /// </summary>
        public override void AddNew()
        {
            base.AddNew();
        }

        protected override DbCommand GetInsertCommand(CommandType commandType)
        {
            DbCommand dbCommand;

            // Create the Database object, using the default database service. The
            // default database service is determined through configuration.
            Database db = GetDatabase();

            switch (commandType)
            {
                case CommandType.StoredProcedure:
                    string sqlCommand = this.SchemaStoredProcedureWithSeparator + "daab_AddGrade";
                    dbCommand = db.GetStoredProcCommand(sqlCommand);

                    CreateParameters(db, dbCommand);

                    return dbCommand;

                case CommandType.Text:
                    this.Query.ClearAll();
                    this.Where.WhereClauseReset();
                    foreach (SchemaItem item in this.SchemaEntries)
                    {
                        if (!(item.IsAutoKey || item.IsComputed))
                        {
                            this.Query.AddInsertColumn(item);
                        }
                    }
                    dbCommand = this.Query.GetInsertCommandWrapper();

                    dbCommand.Parameters.Clear();
                    CreateParameters(db, dbCommand);

                    return dbCommand;

                default:
                    throw new ArgumentException("Invalid CommandType", "commandType");
            }
        }

        protected override DbCommand GetUpdateCommand(CommandType commandType)
        {
            DbCommand dbCommand;

            // Create the Database object, using the default database service. The
            // default database service is determined through configuration.
            Database db = GetDatabase();

            switch (commandType)
            {
                case CommandType.StoredProcedure:
                    string sqlCommand = this.SchemaStoredProcedureWithSeparator + "daab_UpdateGrade";
                    dbCommand = db.GetStoredProcCommand(sqlCommand);

                    CreateParameters(db, dbCommand);

                    return dbCommand;

                case CommandType.Text:
                    this.Query.ClearAll();
                    foreach (SchemaItem item in this.SchemaEntries)
                    {
                        if (!(item.IsAutoKey || item.IsComputed))
                        {
                            this.Query.AddUpdateColumn(item);
                        }
                    }

                    this.Where.WhereClauseReset();
                    dbCommand = this.Query.GetUpdateCommandWrapper();

                    dbCommand.Parameters.Clear();
                    CreateParameters(db, dbCommand);

                    return dbCommand;

                default:
                    throw new ArgumentException("Invalid CommandType", "commandType");
            }
        }

        protected override DbCommand GetDeleteCommand(CommandType commandType)
        {
            DbCommand dbCommand;

            // Create the Database object, using the default database service. The
            // default database service is determined through configuration.
            Database db = GetDatabase();

            switch (commandType)
            {
                case CommandType.StoredProcedure:
                    string sqlCommand = this.SchemaStoredProcedureWithSeparator + "daab_DeleteGrade";
                    dbCommand = db.GetStoredProcCommand(sqlCommand);
                    db.AddInParameter(dbCommand, "GradeId", DbType.Int32, "GradeId", DataRowVersion.Current);

                    return dbCommand;

                case CommandType.Text:
                    this.Query.ClearAll();
                    this.Where.WhereClauseReset();
                    this.Where.GradeId.Operator = WhereParameter.Operand.Equal;
                    dbCommand = this.Query.GetDeleteCommandWrapper();

                    dbCommand.Parameters.Clear();
                    db.AddInParameter(dbCommand, "GradeId", DbType.Int32, "GradeId", DataRowVersion.Current);

                    return dbCommand;

                default:
                    throw new ArgumentException("Invalid CommandType", "commandType");
            }
        }

        private void CreateParameters(Database db, DbCommand dbCommand)
        {
            db.AddInParameter(dbCommand, "GradeId", DbType.Int32, "GradeId", DataRowVersion.Current);
            db.AddInParameter(dbCommand, "Name", DbType.String, "Name", DataRowVersion.Current);
        }

        #region Properties
        public virtual int GradeId
        {
            get
            {
                return this.GetInteger(GradeSchema.GradeId.FieldName);
            }
            set
            {
                this.SetInteger(GradeSchema.GradeId.FieldName, value);
            }
        }
        public virtual string Name
        {
            get
            {
                return this.GetString(GradeSchema.Name.FieldName);
            }
            set
            {
                this.SetString(GradeSchema.Name.FieldName, value);
            }
        }
        public override string TableName
        {
            get { return "Grade"; }
        }

        #endregion

        #region String Properties

        public virtual string sGradeId
        {
            get
            {
                return this.IsColumnNull(GradeSchema.GradeId.FieldName) ? string.Empty : base.GetIntegerAsString(GradeSchema.GradeId.FieldName);
            }
            set
            {
                if (string.Empty == value)
                    this.SetColumnNull(GradeSchema.GradeId.FieldName);
                else
                    this.GradeId = base.SetIntegerAsString(GradeSchema.GradeId.FieldName, value);
            }
        }

        public virtual string s_Name
        {
            get
            {
                return this.IsColumnNull(GradeSchema.Name.FieldName) ? string.Empty : base.GetStringAsString(GradeSchema.Name.FieldName);
            }
            set
            {
                if (string.Empty == value)
                    this.SetColumnNull(GradeSchema.Name.FieldName);
                else
                    this.Name = base.SetStringAsString(GradeSchema.Name.FieldName, value);
            }
        }

        #endregion

        #region Where Clause
        public class WhereClause
        {
            public WhereClause(EasyObject entity)
            {
                this._entity = entity;
            }

            public TearOffWhereParameter TearOff
            {
                get
                {
                    if (_tearOff == null)
                    {
                        _tearOff = new TearOffWhereParameter(this);
                    }

                    return _tearOff;
                }
            }

            #region TearOff's
            public class TearOffWhereParameter
            {
                public TearOffWhereParameter(WhereClause clause)
                {
                    this._clause = clause;
                }


                public WhereParameter GradeId
                {
                    get
                    {
                        WhereParameter wp = new WhereParameter(GradeSchema.GradeId);
                        this._clause._entity.Query.AddWhereParameter(wp);
                        return wp;
                    }
                }

                public WhereParameter Name
                {
                    get
                    {
                        WhereParameter wp = new WhereParameter(GradeSchema.Name);
                        this._clause._entity.Query.AddWhereParameter(wp);
                        return wp;
                    }
                }


                private WhereClause _clause;
            }
            #endregion

            public WhereParameter GradeId
            {
                get
                {
                    if (GradeId_W == null)
                    {
                        GradeId_W = TearOff.GradeId;
                    }
                    return GradeId_W;
                }
            }

            public WhereParameter Name
            {
                get
                {
                    if (_Name_W == null)
                    {
                        _Name_W = TearOff.Name;
                    }
                    return _Name_W;
                }
            }

            private WhereParameter GradeId_W = null;
            private WhereParameter _Name_W = null;

            public void WhereClauseReset()
            {
                GradeId_W = null;
                _Name_W = null;

                this._entity.Query.FlushWhereParameters();

            }

            private EasyObject _entity;
            private TearOffWhereParameter _tearOff;

        }

        public WhereClause Where
        {
            get
            {
                if (_whereClause == null)
                {
                    _whereClause = new WhereClause(this);
                }

                return _whereClause;
            }
        }

        private WhereClause _whereClause = null;
        #endregion

        #region Aggregate Clause
        public class AggregateClause
        {
            public AggregateClause(EasyObject entity)
            {
                this._entity = entity;
            }

            public TearOffAggregateParameter TearOff
            {
                get
                {
                    if (_tearOff == null)
                    {
                        _tearOff = new TearOffAggregateParameter(this);
                    }

                    return _tearOff;
                }
            }

            #region TearOff's
            public class TearOffAggregateParameter
            {
                public TearOffAggregateParameter(AggregateClause clause)
                {
                    this._clause = clause;
                }


                public AggregateParameter GradeId
                {
                    get
                    {
                        AggregateParameter ap = new AggregateParameter(GradeSchema.GradeId);
                        this._clause._entity.Query.AddAggregateParameter(ap);
                        return ap;
                    }
                }

                public AggregateParameter Name
                {
                    get
                    {
                        AggregateParameter ap = new AggregateParameter(GradeSchema.Name);
                        this._clause._entity.Query.AddAggregateParameter(ap);
                        return ap;
                    }
                }

                private AggregateClause _clause;
            }
            #endregion

            public AggregateParameter GradeId
            {
                get
                {
                    if (GradeId_W == null)
                    {
                        GradeId_W = TearOff.GradeId;
                    }
                    return GradeId_W;
                }
            }

            public AggregateParameter Name
            {
                get
                {
                    if (_Name_W == null)
                    {
                        _Name_W = TearOff.Name;
                    }
                    return _Name_W;
                }
            }

            private AggregateParameter GradeId_W = null;
            private AggregateParameter _Name_W = null;

            public void AggregateClauseReset()
            {
                GradeId_W = null;
                _Name_W = null;

                this._entity.Query.FlushAggregateParameters();

            }

            private EasyObject _entity;
            private TearOffAggregateParameter _tearOff;

        }

        public AggregateClause Aggregate
        {
            get
            {
                if (_aggregateClause == null)
                {
                    _aggregateClause = new AggregateClause(this);
                }

                return _aggregateClause;
            }
        }

        private AggregateClause _aggregateClause = null;
        #endregion
    }
}