/*
'===============================================================================
'  Generated From - CSharp_EasyObject_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL      = SQL_DAAB_StoredProcs.vbgen
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easily done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.1.5.1)

using System;
using System.Data;
using System.Data.Common;
using System.Configuration;
using System.Collections;
using System.Collections.Specialized;
using System.Xml;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Data;
using NCI.EasyObjects;

namespace Miami.Substitute.Dal.Generated
{

    #region Schema

    public class PreferredSchema : NCI.EasyObjects.Schema
    {
        private static ArrayList _entries;
        public static SchemaItem PreferredId = new SchemaItem("PreferredId", DbType.Int32, true, false, false, true, false, false);
        public static SchemaItem LocationId = new SchemaItem("LocationId", DbType.Int32, false, false, false, false, false, false);
        public static SchemaItem SubstituteId = new SchemaItem("SubstituteId", DbType.Int32, false, false, false, false, false, false);

        public override ArrayList SchemaEntries
        {
            get
            {
                if (_entries == null)
                {
                    _entries = new ArrayList();
                    _entries.Add(PreferredSchema.PreferredId);
                    _entries.Add(PreferredSchema.LocationId);
                    _entries.Add(PreferredSchema.SubstituteId);
                }
                return _entries;
            }
        }
    }
    #endregion

    public abstract class Preferred : EasyObject
    {

        public Preferred()
        {
            PreferredSchema _schema = new PreferredSchema();
            this.SchemaEntries = _schema.SchemaEntries;
            this.SchemaGlobal = "dbo";
        }

        public override void FlushData()
        {
            this._whereClause = null;
            this._aggregateClause = null;
            base.FlushData();
        }

        /// <summary>
        /// Loads the business object with info from the database, based on the requested primary key.
        /// </summary>
        /// <param name="PreferredId"></param>
        /// <returns>A Boolean indicating success or failure of the query</returns>
        public bool LoadByPrimaryKey(int PreferredId)
        {
            switch (this.DefaultCommandType)
            {
                case CommandType.StoredProcedure:
                    ListDictionary parameters = new ListDictionary();

                    // Add in parameters
                    parameters.Add(PreferredSchema.PreferredId.FieldName, PreferredId);

                    return base.LoadFromSql(this.SchemaStoredProcedureWithSeparator + "daab_GetPreferred", parameters, CommandType.StoredProcedure);

                case CommandType.Text:
                    this.Query.ClearAll();
                    this.Where.WhereClauseReset();
                    this.Where.PreferredId.Value = PreferredId;
                    return this.Query.Load();

                default:
                    throw new ArgumentException("Invalid CommandType", "commandType");
            }
        }

        /// <summary>
        /// Loads all records from the table.
        /// </summary>
        /// <returns>A Boolean indicating success or failure of the query</returns>
        public bool LoadAll()
        {
            switch (this.DefaultCommandType)
            {
                case CommandType.StoredProcedure:
                    return base.LoadFromSql(this.SchemaStoredProcedureWithSeparator + "daab_GetAllPreferred", null, CommandType.StoredProcedure);

                case CommandType.Text:
                    this.Query.ClearAll();
                    this.Where.WhereClauseReset();
                    return this.Query.Load();

                default:
                    throw new ArgumentException("Invalid CommandType", "commandType");
            }
        }

        /// <summary>
        /// Adds a new record to the internal table.
        /// </summary>
        public override void AddNew()
        {
            base.AddNew();
        }

        protected override DbCommand GetInsertCommand(CommandType commandType)
        {
            DbCommand dbCommand;

            // Create the Database object, using the default database service. The
            // default database service is determined through configuration.
            Database db = GetDatabase();

            switch (commandType)
            {
                case CommandType.StoredProcedure:
                    string sqlCommand = this.SchemaStoredProcedureWithSeparator + "daab_AddPreferred";
                    dbCommand = db.GetStoredProcCommand(sqlCommand);

                    db.AddParameter(dbCommand, "PreferredId", DbType.Int32, 0, ParameterDirection.Output, true, 0, 0, "PreferredId", DataRowVersion.Default, Convert.DBNull);
                    CreateParameters(db, dbCommand);

                    return dbCommand;

                case CommandType.Text:
                    this.Query.ClearAll();
                    this.Where.WhereClauseReset();
                    foreach (SchemaItem item in this.SchemaEntries)
                    {
                        if (!(item.IsAutoKey || item.IsComputed))
                        {
                            this.Query.AddInsertColumn(item);
                        }
                    }
                    dbCommand = this.Query.GetInsertCommandWrapper();

                    dbCommand.Parameters.Clear();
                    CreateParameters(db, dbCommand);
                    db.AddParameter(dbCommand, "PreferredId", DbType.Int32, 0, ParameterDirection.Output, true, 0, 0, "PreferredId", DataRowVersion.Default, Convert.DBNull);

                    return dbCommand;

                default:
                    throw new ArgumentException("Invalid CommandType", "commandType");
            }
        }

        protected override DbCommand GetUpdateCommand(CommandType commandType)
        {
            DbCommand dbCommand;

            // Create the Database object, using the default database service. The
            // default database service is determined through configuration.
            Database db = GetDatabase();

            switch (commandType)
            {
                case CommandType.StoredProcedure:
                    string sqlCommand = this.SchemaStoredProcedureWithSeparator + "daab_UpdatePreferred";
                    dbCommand = db.GetStoredProcCommand(sqlCommand);

                    db.AddInParameter(dbCommand, "PreferredId", DbType.Int32, "PreferredId", DataRowVersion.Current);
                    CreateParameters(db, dbCommand);

                    return dbCommand;

                case CommandType.Text:
                    this.Query.ClearAll();
                    foreach (SchemaItem item in this.SchemaEntries)
                    {
                        if (!(item.IsAutoKey || item.IsComputed))
                        {
                            this.Query.AddUpdateColumn(item);
                        }
                    }

                    this.Where.WhereClauseReset();
                    this.Where.PreferredId.Operator = WhereParameter.Operand.Equal;
                    dbCommand = this.Query.GetUpdateCommandWrapper();

                    dbCommand.Parameters.Clear();
                    CreateParameters(db, dbCommand);
                    db.AddInParameter(dbCommand, "PreferredId", DbType.Int32, "PreferredId", DataRowVersion.Current);

                    return dbCommand;

                default:
                    throw new ArgumentException("Invalid CommandType", "commandType");
            }
        }

        protected override DbCommand GetDeleteCommand(CommandType commandType)
        {
            DbCommand dbCommand;

            // Create the Database object, using the default database service. The
            // default database service is determined through configuration.
            Database db = GetDatabase();

            switch (commandType)
            {
                case CommandType.StoredProcedure:
                    string sqlCommand = this.SchemaStoredProcedureWithSeparator + "daab_DeletePreferred";
                    dbCommand = db.GetStoredProcCommand(sqlCommand);
                    db.AddInParameter(dbCommand, "PreferredId", DbType.Int32, "PreferredId", DataRowVersion.Current);

                    return dbCommand;

                case CommandType.Text:
                    this.Query.ClearAll();
                    this.Where.WhereClauseReset();
                    this.Where.PreferredId.Operator = WhereParameter.Operand.Equal;
                    dbCommand = this.Query.GetDeleteCommandWrapper();

                    dbCommand.Parameters.Clear();
                    db.AddInParameter(dbCommand, "PreferredId", DbType.Int32, "PreferredId", DataRowVersion.Current);

                    return dbCommand;

                default:
                    throw new ArgumentException("Invalid CommandType", "commandType");
            }
        }

        private void CreateParameters(Database db, DbCommand dbCommand)
        {
            db.AddInParameter(dbCommand, "LocationId", DbType.Int32, "LocationId", DataRowVersion.Current);
            db.AddInParameter(dbCommand, "SubstituteId", DbType.Int32, "SubstituteId", DataRowVersion.Current);
        }

        #region Properties
        public virtual int PreferredId
        {
            get
            {
                return this.GetInteger(PreferredSchema.PreferredId.FieldName);
            }
            set
            {
                this.SetInteger(PreferredSchema.PreferredId.FieldName, value);
            }
        }
        public virtual int LocationId
        {
            get
            {
                return this.GetInteger(PreferredSchema.LocationId.FieldName);
            }
            set
            {
                this.SetInteger(PreferredSchema.LocationId.FieldName, value);
            }
        }
        public virtual int SubstituteId
        {
            get
            {
                return this.GetInteger(PreferredSchema.SubstituteId.FieldName);
            }
            set
            {
                this.SetInteger(PreferredSchema.SubstituteId.FieldName, value);
            }
        }

        public override string TableName
        {
            get { return "Preferred"; }
        }

        #endregion

        #region String Properties

        public virtual string sPreferredId
        {
            get
            {
                return this.IsColumnNull(PreferredSchema.PreferredId.FieldName) ? string.Empty : base.GetIntegerAsString(PreferredSchema.PreferredId.FieldName);
            }
            set
            {
                if (string.Empty == value)
                    this.SetColumnNull(PreferredSchema.PreferredId.FieldName);
                else
                    this.PreferredId = base.SetIntegerAsString(PreferredSchema.PreferredId.FieldName, value);
            }
        }

        public virtual string s_LocationId
        {
            get
            {
                return this.IsColumnNull(PreferredSchema.LocationId.FieldName) ? string.Empty : base.GetIntegerAsString(PreferredSchema.LocationId.FieldName);
            }
            set
            {
                if (string.Empty == value)
                    this.SetColumnNull(PreferredSchema.LocationId.FieldName);
                else
                    this.LocationId = base.SetIntegerAsString(PreferredSchema.LocationId.FieldName, value);
            }
        }

        public virtual string s_SubstituteId
        {
            get
            {
                return this.IsColumnNull(PreferredSchema.SubstituteId.FieldName) ? string.Empty : base.GetIntegerAsString(PreferredSchema.SubstituteId.FieldName);
            }
            set
            {
                if (string.Empty == value)
                    this.SetColumnNull(PreferredSchema.SubstituteId.FieldName);
                else
                    this.SubstituteId = base.SetIntegerAsString(PreferredSchema.SubstituteId.FieldName, value);
            }
        }


        #endregion

        #region Where Clause
        public class WhereClause
        {
            public WhereClause(EasyObject entity)
            {
                this._entity = entity;
            }

            public TearOffWhereParameter TearOff
            {
                get
                {
                    if (_tearOff == null)
                    {
                        _tearOff = new TearOffWhereParameter(this);
                    }

                    return _tearOff;
                }
            }

            #region TearOff's
            public class TearOffWhereParameter
            {
                public TearOffWhereParameter(WhereClause clause)
                {
                    this._clause = clause;
                }


                public WhereParameter PreferredId
                {
                    get
                    {
                        WhereParameter wp = new WhereParameter(PreferredSchema.PreferredId);
                        this._clause._entity.Query.AddWhereParameter(wp);
                        return wp;
                    }
                }

                public WhereParameter LocationId
                {
                    get
                    {
                        WhereParameter wp = new WhereParameter(PreferredSchema.LocationId);
                        this._clause._entity.Query.AddWhereParameter(wp);
                        return wp;
                    }
                }

                public WhereParameter SubstituteId
                {
                    get
                    {
                        WhereParameter wp = new WhereParameter(PreferredSchema.SubstituteId);
                        this._clause._entity.Query.AddWhereParameter(wp);
                        return wp;
                    }
                }


                private WhereClause _clause;
            }
            #endregion

            public WhereParameter PreferredId
            {
                get
                {
                    if (PreferredId_W == null)
                    {
                        PreferredId_W = TearOff.PreferredId;
                    }
                    return PreferredId_W;
                }
            }

            public WhereParameter LocationId
            {
                get
                {
                    if (_LocationId_W == null)
                    {
                        _LocationId_W = TearOff.LocationId;
                    }
                    return _LocationId_W;
                }
            }

            public WhereParameter SubstituteId
            {
                get
                {
                    if (_SubstituteId_W == null)
                    {
                        _SubstituteId_W = TearOff.SubstituteId;
                    }
                    return _SubstituteId_W;
                }
            }

            private WhereParameter PreferredId_W = null;
            private WhereParameter _LocationId_W = null;
            private WhereParameter _SubstituteId_W = null;

            public void WhereClauseReset()
            {
                PreferredId_W = null;
                _LocationId_W = null;
                _SubstituteId_W = null;

                this._entity.Query.FlushWhereParameters();

            }

            private EasyObject _entity;
            private TearOffWhereParameter _tearOff;

        }

        public WhereClause Where
        {
            get
            {
                if (_whereClause == null)
                {
                    _whereClause = new WhereClause(this);
                }

                return _whereClause;
            }
        }

        private WhereClause _whereClause = null;
        #endregion

        #region Aggregate Clause
        public class AggregateClause
        {
            public AggregateClause(EasyObject entity)
            {
                this._entity = entity;
            }

            public TearOffAggregateParameter TearOff
            {
                get
                {
                    if (_tearOff == null)
                    {
                        _tearOff = new TearOffAggregateParameter(this);
                    }

                    return _tearOff;
                }
            }

            #region TearOff's
            public class TearOffAggregateParameter
            {
                public TearOffAggregateParameter(AggregateClause clause)
                {
                    this._clause = clause;
                }


                public AggregateParameter PreferredId
                {
                    get
                    {
                        AggregateParameter ap = new AggregateParameter(PreferredSchema.PreferredId);
                        this._clause._entity.Query.AddAggregateParameter(ap);
                        return ap;
                    }
                }

                public AggregateParameter LocationId
                {
                    get
                    {
                        AggregateParameter ap = new AggregateParameter(PreferredSchema.LocationId);
                        this._clause._entity.Query.AddAggregateParameter(ap);
                        return ap;
                    }
                }

                public AggregateParameter SubstituteId
                {
                    get
                    {
                        AggregateParameter ap = new AggregateParameter(PreferredSchema.SubstituteId);
                        this._clause._entity.Query.AddAggregateParameter(ap);
                        return ap;
                    }
                }


                private AggregateClause _clause;
            }
            #endregion

            public AggregateParameter PreferredId
            {
                get
                {
                    if (PreferredId_W == null)
                    {
                        PreferredId_W = TearOff.PreferredId;
                    }
                    return PreferredId_W;
                }
            }

            public AggregateParameter LocationId
            {
                get
                {
                    if (_LocationId_W == null)
                    {
                        _LocationId_W = TearOff.LocationId;
                    }
                    return _LocationId_W;
                }
            }

            public AggregateParameter SubstituteId
            {
                get
                {
                    if (_SubstituteId_W == null)
                    {
                        _SubstituteId_W = TearOff.SubstituteId;
                    }
                    return _SubstituteId_W;
                }
            }

            private AggregateParameter PreferredId_W = null;
            private AggregateParameter _LocationId_W = null;
            private AggregateParameter _SubstituteId_W = null;

            public void AggregateClauseReset()
            {
                PreferredId_W = null;
                _LocationId_W = null;
                _SubstituteId_W = null;

                this._entity.Query.FlushAggregateParameters();

            }

            private EasyObject _entity;
            private TearOffAggregateParameter _tearOff;

        }

        public AggregateClause Aggregate
        {
            get
            {
                if (_aggregateClause == null)
                {
                    _aggregateClause = new AggregateClause(this);
                }

                return _aggregateClause;
            }
        }

        private AggregateClause _aggregateClause = null;
        #endregion
    }
}