/*
'===============================================================================
'  Generated From - CSharp_EasyObject_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL      = SQL_DAAB_StoredProcs.vbgen
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easily done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.1.5.1)

using System;
using System.Data;
using System.Data.Common;
using System.Configuration;
using System.Collections;
using System.Collections.Specialized;
using System.Xml;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Data;
using NCI.EasyObjects;

namespace Miami.Substitute.Dal.Generated
{

	#region Schema

	public class TeacherSchema : NCI.EasyObjects.Schema
	{
		private static ArrayList _entries;
		public static SchemaItem TeacherId = new SchemaItem("TeacherId", DbType.Int32, false, false, false, true, false, false);
		public static SchemaItem Active = new SchemaItem("Active", DbType.Boolean, false, false, false, false, false, true);
		public static SchemaItem UserProfileId = new SchemaItem("UserProfileId", DbType.Int32, false, false, false, false, true, false);

		public override ArrayList SchemaEntries
		{
			get
			{
				if (_entries == null )
				{
					_entries = new ArrayList();
					_entries.Add(TeacherSchema.TeacherId);
					_entries.Add(TeacherSchema.Active);
					_entries.Add(TeacherSchema.UserProfileId);
				}
				return _entries;
			}
		}
	}
	#endregion

	public abstract class Teacher : EasyObject
	{

		public Teacher()
		{
			TeacherSchema _schema = new TeacherSchema();
			this.SchemaEntries = _schema.SchemaEntries;
			this.SchemaGlobal = "dbo";
		}
		
		public override void FlushData() 	 
		{ 	 
			this._whereClause = null; 	 
			this._aggregateClause = null; 	 
			base.FlushData(); 	 
		}
			   
		/// <summary>
		/// Loads the business object with info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="TeacherId"></param>
		/// <returns>A Boolean indicating success or failure of the query</returns>
		public bool LoadByPrimaryKey(int TeacherId)
		{
			switch(this.DefaultCommandType)
			{
				case CommandType.StoredProcedure:
					ListDictionary parameters = new ListDictionary();

					// Add in parameters
					parameters.Add(TeacherSchema.TeacherId.FieldName, TeacherId);

					return base.LoadFromSql(this.SchemaStoredProcedureWithSeparator + "daab_GetTeacher", parameters, CommandType.StoredProcedure);

				case CommandType.Text:
					this.Query.ClearAll();
					this.Where.WhereClauseReset();
					this.Where.TeacherId.Value = TeacherId;
					return this.Query.Load();

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}
	
		/// <summary>
		/// Loads all records from the table.
		/// </summary>
		/// <returns>A Boolean indicating success or failure of the query</returns>
		public bool LoadAll()
		{
			switch(this.DefaultCommandType)
			{
				case CommandType.StoredProcedure:
					return base.LoadFromSql(this.SchemaStoredProcedureWithSeparator + "daab_GetAllTeacher", null, CommandType.StoredProcedure);

				case CommandType.Text:
					this.Query.ClearAll();
					this.Where.WhereClauseReset();
					return this.Query.Load();

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}

		/// <summary>
		/// Adds a new record to the internal table.
		/// </summary>
		public override void AddNew()
		{
			base.AddNew();
		}

		protected override DbCommand GetInsertCommand(CommandType commandType)
		{	
			DbCommand dbCommand;

			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = GetDatabase();

			switch(commandType)
			{
				case CommandType.StoredProcedure:
					string sqlCommand = this.SchemaStoredProcedureWithSeparator + "daab_AddTeacher";
					dbCommand = db.GetStoredProcCommand(sqlCommand);

					CreateParameters(db, dbCommand);
					
					return dbCommand;

				case CommandType.Text:
					this.Query.ClearAll();
					this.Where.WhereClauseReset();
					foreach(SchemaItem item in this.SchemaEntries)
					{
						if (!(item.IsAutoKey || item.IsComputed))
						{
							this.Query.AddInsertColumn(item);
						}
					}
					dbCommand = this.Query.GetInsertCommandWrapper();

					dbCommand.Parameters.Clear();
					CreateParameters(db, dbCommand);
					
					return dbCommand;

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}

		protected override DbCommand GetUpdateCommand(CommandType commandType)
		{
            DbCommand dbCommand;

			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = GetDatabase();

			switch(commandType)
			{
				case CommandType.StoredProcedure:
					string sqlCommand = this.SchemaStoredProcedureWithSeparator + "daab_UpdateTeacher";
					dbCommand = db.GetStoredProcCommand(sqlCommand);

					CreateParameters(db, dbCommand);
					
					return dbCommand;

				case CommandType.Text:
					this.Query.ClearAll();
					foreach(SchemaItem item in this.SchemaEntries)
					{
						if (!(item.IsAutoKey || item.IsComputed))
						{
							this.Query.AddUpdateColumn(item);
						}
					}

					this.Where.WhereClauseReset();
					dbCommand = this.Query.GetUpdateCommandWrapper();

					dbCommand.Parameters.Clear();
					CreateParameters(db, dbCommand);
					
					return dbCommand;

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}

		protected override DbCommand GetDeleteCommand(CommandType commandType)
		{
            DbCommand dbCommand;

			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = GetDatabase();

			switch(commandType)
			{
				case CommandType.StoredProcedure:
					string sqlCommand = this.SchemaStoredProcedureWithSeparator + "daab_DeleteTeacher";
					dbCommand = db.GetStoredProcCommand(sqlCommand);
					db.AddInParameter(dbCommand, "TeacherId", DbType.Int32, "TeacherId", DataRowVersion.Current);
					
					return dbCommand;

				case CommandType.Text:
					this.Query.ClearAll();
					this.Where.WhereClauseReset();
					this.Where.TeacherId.Operator = WhereParameter.Operand.Equal;
					dbCommand = this.Query.GetDeleteCommandWrapper();

					dbCommand.Parameters.Clear();
					db.AddInParameter(dbCommand, "TeacherId", DbType.Int32, "TeacherId", DataRowVersion.Current);
					
					return dbCommand;

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}

		private void CreateParameters(Database db, DbCommand dbCommand)
		{
			db.AddInParameter(dbCommand, "TeacherId", DbType.Int32, "TeacherId", DataRowVersion.Current);
			db.AddInParameter(dbCommand, "Active", DbType.Boolean, "Active", DataRowVersion.Current);
			db.AddInParameter(dbCommand, "UserProfileId", DbType.Int32, "UserProfileId", DataRowVersion.Current);
		}
		
		#region Properties
		public virtual int TeacherId
		{
			get
			{
				return this.GetInteger(TeacherSchema.TeacherId.FieldName);
	    	}
			set
			{
				this.SetInteger(TeacherSchema.TeacherId.FieldName, value);
			}
		}
		public virtual bool Active
		{
			get
			{
				return this.GetBoolean(TeacherSchema.Active.FieldName);
	    	}
			set
			{
				this.SetBoolean(TeacherSchema.Active.FieldName, value);
			}
		}
		public virtual int UserProfileId
		{
			get
			{
				return this.GetInteger(TeacherSchema.UserProfileId.FieldName);
	    	}
			set
			{
				this.SetInteger(TeacherSchema.UserProfileId.FieldName, value);
			}
		}

		public override string TableName
		{
			get { return "Teacher"; }
		}
		
		#endregion		
		
		#region String Properties
	
		public virtual string sTeacherId
	    {
			get
	        {
				return this.IsColumnNull(TeacherSchema.TeacherId.FieldName) ? string.Empty : base.GetIntegerAsString(TeacherSchema.TeacherId.FieldName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(TeacherSchema.TeacherId.FieldName);
				else
					this.TeacherId = base.SetIntegerAsString(TeacherSchema.TeacherId.FieldName, value);
			}
		}

		public virtual string s_Active
	    {
			get
	        {
				return this.IsColumnNull(TeacherSchema.Active.FieldName) ? string.Empty : base.GetBooleanAsString(TeacherSchema.Active.FieldName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(TeacherSchema.Active.FieldName);
				else
					this.Active = base.SetBooleanAsString(TeacherSchema.Active.FieldName, value);
			}
		}

		public virtual string sUserProfileId
	    {
			get
	        {
				return this.IsColumnNull(TeacherSchema.UserProfileId.FieldName) ? string.Empty : base.GetIntegerAsString(TeacherSchema.UserProfileId.FieldName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(TeacherSchema.UserProfileId.FieldName);
				else
					this.UserProfileId = base.SetIntegerAsString(TeacherSchema.UserProfileId.FieldName, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(EasyObject entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter TeacherId
				{
					get
					{
							WhereParameter wp = new WhereParameter(TeacherSchema.TeacherId);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}

				public WhereParameter Active
				{
					get
					{
							WhereParameter wp = new WhereParameter(TeacherSchema.Active);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}

				public WhereParameter UserProfileId
				{
					get
					{
							WhereParameter wp = new WhereParameter(TeacherSchema.UserProfileId);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter TeacherId
		    {
				get
		        {
					if(TeacherId_W == null)
	        	    {
						TeacherId_W = TearOff.TeacherId;
					}
					return TeacherId_W;
				}
			}

			public WhereParameter Active
		    {
				get
		        {
					if(_Active_W == null)
	        	    {
						_Active_W = TearOff.Active;
					}
					return _Active_W;
				}
			}

			public WhereParameter UserProfileId
		    {
				get
		        {
					if(UserProfileId_W == null)
	        	    {
						UserProfileId_W = TearOff.UserProfileId;
					}
					return UserProfileId_W;
				}
			}

			private WhereParameter TeacherId_W = null;
			private WhereParameter _Active_W = null;
			private WhereParameter UserProfileId_W = null;

			public void WhereClauseReset()
			{
				TeacherId_W = null;
				_Active_W = null;
				UserProfileId_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private EasyObject _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
		
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(EasyObject entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter TeacherId
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(TeacherSchema.TeacherId);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}

				public AggregateParameter Active
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(TeacherSchema.Active);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}

				public AggregateParameter UserProfileId
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(TeacherSchema.UserProfileId);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter TeacherId
		    {
				get
		        {
					if(TeacherId_W == null)
	        	    {
						TeacherId_W = TearOff.TeacherId;
					}
					return TeacherId_W;
				}
			}

			public AggregateParameter Active
		    {
				get
		        {
					if(_Active_W == null)
	        	    {
						_Active_W = TearOff.Active;
					}
					return _Active_W;
				}
			}

			public AggregateParameter UserProfileId
		    {
				get
		        {
					if(UserProfileId_W == null)
	        	    {
						UserProfileId_W = TearOff.UserProfileId;
					}
					return UserProfileId_W;
				}
			}

			private AggregateParameter TeacherId_W = null;
			private AggregateParameter _Active_W = null;
			private AggregateParameter UserProfileId_W = null;

			public void AggregateClauseReset()
			{
				TeacherId_W = null;
				_Active_W = null;
				UserProfileId_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private EasyObject _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	}
}
